package pe.unsch.sistemaescalafonario.entity;
// Generated 21-mar-2018 18:08:39 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Datoshijos generated by hbm2java
 */
public class Datoshijos  implements java.io.Serializable {


     private int id;
     private Datosfamilia datosfamilia;
     private String dnihijo;
     private String appathijo;
     private String apmathijo;
     private String nombreshijo;
     private Date fechanachijo;
     private String sexo;

    public Datoshijos() {
    }

	
    public Datoshijos(int id, Datosfamilia datosfamilia, String dnihijo, String appathijo, String apmathijo, String nombreshijo, Date fechanachijo) {
        this.id = id;
        this.datosfamilia = datosfamilia;
        this.dnihijo = dnihijo;
        this.appathijo = appathijo;
        this.apmathijo = apmathijo;
        this.nombreshijo = nombreshijo;
        this.fechanachijo = fechanachijo;
    }
    public Datoshijos(int id, Datosfamilia datosfamilia, String dnihijo, String appathijo, String apmathijo, String nombreshijo, Date fechanachijo, String sexo) {
       this.id = id;
       this.datosfamilia = datosfamilia;
       this.dnihijo = dnihijo;
       this.appathijo = appathijo;
       this.apmathijo = apmathijo;
       this.nombreshijo = nombreshijo;
       this.fechanachijo = fechanachijo;
       this.sexo = sexo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Datosfamilia getDatosfamilia() {
        return this.datosfamilia;
    }
    
    public void setDatosfamilia(Datosfamilia datosfamilia) {
        this.datosfamilia = datosfamilia;
    }
    public String getDnihijo() {
        return this.dnihijo;
    }
    
    public void setDnihijo(String dnihijo) {
        this.dnihijo = dnihijo;
    }
    public String getAppathijo() {
        return this.appathijo;
    }
    
    public void setAppathijo(String appathijo) {
        this.appathijo = appathijo;
    }
    public String getApmathijo() {
        return this.apmathijo;
    }
    
    public void setApmathijo(String apmathijo) {
        this.apmathijo = apmathijo;
    }
    public String getNombreshijo() {
        return this.nombreshijo;
    }
    
    public void setNombreshijo(String nombreshijo) {
        this.nombreshijo = nombreshijo;
    }
    public Date getFechanachijo() {
        return this.fechanachijo;
    }
    
    public void setFechanachijo(Date fechanachijo) {
        this.fechanachijo = fechanachijo;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }




}


