package pe.unsch.sistemaescalafonario.entity;
// Generated 21-mar-2018 18:08:39 by Hibernate Tools 4.3.1



/**
 * Datosacademicos generated by hbm2java
 */
public class Datosacademicos  implements java.io.Serializable {


     private int id;
     private Empleado empleado;
     private String gradoinstruccion;
     private String nombreinstitucion;
     private String condicion;
     private Integer anioegreso;
     private String especialidad;

    public Datosacademicos() {
    }

	
    public Datosacademicos(int id, Empleado empleado, String gradoinstruccion, String nombreinstitucion, String condicion) {
        this.id = id;
        this.empleado = empleado;
        this.gradoinstruccion = gradoinstruccion;
        this.nombreinstitucion = nombreinstitucion;
        this.condicion = condicion;
    }
    public Datosacademicos(int id, Empleado empleado, String gradoinstruccion, String nombreinstitucion, String condicion, Integer anioegreso, String especialidad) {
       this.id = id;
       this.empleado = empleado;
       this.gradoinstruccion = gradoinstruccion;
       this.nombreinstitucion = nombreinstitucion;
       this.condicion = condicion;
       this.anioegreso = anioegreso;
       this.especialidad = especialidad;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getGradoinstruccion() {
        return this.gradoinstruccion;
    }
    
    public void setGradoinstruccion(String gradoinstruccion) {
        this.gradoinstruccion = gradoinstruccion;
    }
    public String getNombreinstitucion() {
        return this.nombreinstitucion;
    }
    
    public void setNombreinstitucion(String nombreinstitucion) {
        this.nombreinstitucion = nombreinstitucion;
    }
    public String getCondicion() {
        return this.condicion;
    }
    
    public void setCondicion(String condicion) {
        this.condicion = condicion;
    }
    public Integer getAnioegreso() {
        return this.anioegreso;
    }
    
    public void setAnioegreso(Integer anioegreso) {
        this.anioegreso = anioegreso;
    }
    public String getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }




}


