package pe.unsch.sistemaescalafonario.entity;
// Generated 21-mar-2018 18:08:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Distrito generated by hbm2java
 */
public class Distrito  implements java.io.Serializable {


     private int id;
     private Provincia provincia;
     private String nombredistrito;
     

    public Distrito() {
    }

	
    public Distrito(int id, Provincia provincia, String nombredistrito) {
        this.id = id;
        this.provincia = provincia;
        this.nombredistrito = nombredistrito;
    }
    
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public String getNombredistrito() {
        return this.nombredistrito;
    }
    
    public void setNombredistrito(String nombredistrito) {
        this.nombredistrito = nombredistrito;
    }
 

}


