package pe.unsch.sistemaescalafonario.entity;
// Generated 21-mar-2018 18:08:39 by Hibernate Tools 4.3.1



/**
 * Docente generated by hbm2java
 */
public class Docente  implements java.io.Serializable {


     private int id;
     private Empleado empleado;
     private int codigodocente;
     private String categoriadocente;
     private String regimendedicacion;
     private String nivelremunerativodoc;

    public Docente() {
    }

	
    public Docente(int id, Empleado empleado, int codigodocente) {
        this.id = id;
        this.empleado = empleado;
        this.codigodocente = codigodocente;
    }
    public Docente(int id, Empleado empleado, int codigodocente, String categoriadocente, String regimendedicacion, String nivelremunerativodoc) {
       this.id = id;
       this.empleado = empleado;
       this.codigodocente = codigodocente;
       this.categoriadocente = categoriadocente;
       this.regimendedicacion = regimendedicacion;
       this.nivelremunerativodoc = nivelremunerativodoc;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public int getCodigodocente() {
        return this.codigodocente;
    }
    
    public void setCodigodocente(int codigodocente) {
        this.codigodocente = codigodocente;
    }
    public String getCategoriadocente() {
        return this.categoriadocente;
    }
    
    public void setCategoriadocente(String categoriadocente) {
        this.categoriadocente = categoriadocente;
    }
    public String getRegimendedicacion() {
        return this.regimendedicacion;
    }
    
    public void setRegimendedicacion(String regimendedicacion) {
        this.regimendedicacion = regimendedicacion;
    }
    public String getNivelremunerativodoc() {
        return this.nivelremunerativodoc;
    }
    
    public void setNivelremunerativodoc(String nivelremunerativodoc) {
        this.nivelremunerativodoc = nivelremunerativodoc;
    }




}


