package pe.unsch.sistemaescalafonario.entity;
// Generated 21-mar-2018 18:08:39 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int id;
     private Distrito distrito;
     private String dni;
     private String apellidopaterno;
     private String apellidomaterno;
     private String nombres;
     private Date fechanacimiento;
     private String sexo;
     private String estadocivil;
     private String direccion;
     private String celular;
     private String correoelectronico;
     private String gruposanguineo;
     private String sistemapensionario;
     private String ruc;
     private Boolean mayoringreso;
     private Boolean afiliacionsindicato;
    

    public Empleado() {
    }

	
    public Empleado(int id, Distrito distrito, String dni, String apellidopaterno, String apellidomaterno, String nombres, Date fechanacimiento, String sexo) {
        this.id = id;
        this.distrito = distrito;
        this.dni = dni;
        this.apellidopaterno = apellidopaterno;
        this.apellidomaterno = apellidomaterno;
        this.nombres = nombres;
        this.fechanacimiento = fechanacimiento;
        this.sexo = sexo;
    }
    public Empleado(int id, Distrito distrito, String dni, String apellidopaterno, String apellidomaterno, String nombres, Date fechanacimiento, String sexo, String estadocivil, String direccion, String celular, String correoelectronico, String gruposanguineo, String sistemapensionario, String ruc, Boolean mayoringreso, Boolean afiliacionsindicato) {
       this.id = id;
       this.distrito = distrito;
       this.dni = dni;
       this.apellidopaterno = apellidopaterno;
       this.apellidomaterno = apellidomaterno;
       this.nombres = nombres;
       this.fechanacimiento = fechanacimiento;
       this.sexo = sexo;
       this.estadocivil = estadocivil;
       this.direccion = direccion;
       this.celular = celular;
       this.correoelectronico = correoelectronico;
       this.gruposanguineo = gruposanguineo;
       this.sistemapensionario = sistemapensionario;
       this.ruc = ruc;
       this.mayoringreso = mayoringreso;
       this.afiliacionsindicato = afiliacionsindicato;
      
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Distrito getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(Distrito distrito) {
        this.distrito = distrito;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getApellidopaterno() {
        return this.apellidopaterno;
    }
    
    public void setApellidopaterno(String apellidopaterno) {
        this.apellidopaterno = apellidopaterno;
    }
    public String getApellidomaterno() {
        return this.apellidomaterno;
    }
    
    public void setApellidomaterno(String apellidomaterno) {
        this.apellidomaterno = apellidomaterno;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public Date getFechanacimiento() {
        return this.fechanacimiento;
    }
    
    public void setFechanacimiento(Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getEstadocivil() {
        return this.estadocivil;
    }
    
    public void setEstadocivil(String estadocivil) {
        this.estadocivil = estadocivil;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getCorreoelectronico() {
        return this.correoelectronico;
    }
    
    public void setCorreoelectronico(String correoelectronico) {
        this.correoelectronico = correoelectronico;
    }
    public String getGruposanguineo() {
        return this.gruposanguineo;
    }
    
    public void setGruposanguineo(String gruposanguineo) {
        this.gruposanguineo = gruposanguineo;
    }
    public String getSistemapensionario() {
        return this.sistemapensionario;
    }
    
    public void setSistemapensionario(String sistemapensionario) {
        this.sistemapensionario = sistemapensionario;
    }
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    public Boolean getMayoringreso() {
        return this.mayoringreso;
    }
    
    public void setMayoringreso(Boolean mayoringreso) {
        this.mayoringreso = mayoringreso;
    }
    public Boolean getAfiliacionsindicato() {
        return this.afiliacionsindicato;
    }
    
    public void setAfiliacionsindicato(Boolean afiliacionsindicato) {
        this.afiliacionsindicato = afiliacionsindicato;
    }
   

}


