package pe.unsch.sistemaescalafonario.entity;
// Generated 21-mar-2018 18:08:39 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Escalafon generated by hbm2java
 */
public class Escalafon  implements java.io.Serializable {


     private int id;
     private Empleado empleado;
     private String resuelve;
     private String cargo;
     private String descripcion;
     private String resolucion;
     private String numresolucion;
     private Integer anioresolucion;
     private Date delfecha;
     private Date alfecha;
     private Date fecharesolucion;

    public Escalafon() {
    }

	
    public Escalafon(int id, Empleado empleado) {
        this.id = id;
        this.empleado = empleado;
    }
    public Escalafon(int id, Empleado empleado, String resuelve, String cargo, String descripcion, String resolucion, String numresolucion, Integer anioresolucion, Date delfecha, Date alfecha, Date fecharesolucion) {
       this.id = id;
       this.empleado = empleado;
       this.resuelve = resuelve;
       this.cargo = cargo;
       this.descripcion = descripcion;
       this.resolucion = resolucion;
       this.numresolucion = numresolucion;
       this.anioresolucion = anioresolucion;
       this.delfecha = delfecha;
       this.alfecha = alfecha;
       this.fecharesolucion = fecharesolucion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getResuelve() {
        return this.resuelve;
    }
    
    public void setResuelve(String resuelve) {
        this.resuelve = resuelve;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getResolucion() {
        return this.resolucion;
    }
    
    public void setResolucion(String resolucion) {
        this.resolucion = resolucion;
    }
    public String getNumresolucion() {
        return this.numresolucion;
    }
    
    public void setNumresolucion(String numresolucion) {
        this.numresolucion = numresolucion;
    }
    public Integer getAnioresolucion() {
        return this.anioresolucion;
    }
    
    public void setAnioresolucion(Integer anioresolucion) {
        this.anioresolucion = anioresolucion;
    }
    public Date getDelfecha() {
        return this.delfecha;
    }
    
    public void setDelfecha(Date delfecha) {
        this.delfecha = delfecha;
    }
    public Date getAlfecha() {
        return this.alfecha;
    }
    
    public void setAlfecha(Date alfecha) {
        this.alfecha = alfecha;
    }
    public Date getFecharesolucion() {
        return this.fecharesolucion;
    }
    
    public void setFecharesolucion(Date fecharesolucion) {
        this.fecharesolucion = fecharesolucion;
    }




}


